# https://huggingface.co/datasets/noahcao/dancetrack/tree/main
download:
  runs_url: null
  dataset_url: "https://huggingface.co/datasets/noahcao/dancetrack/resolve/main/test1.zip"

benchmark:
  source: "boxmot/engine/trackeval/data/test1"
  split: "val"
  eval_classes:
    1: pedestrian
