# https://motchallenge.net/data/MOT17/
download:
  runs_url: "https://github.com/mikel-brostrom/boxmot/releases/download/v16.0.11/runs.zip"
  dataset_url: "https://github.com/mikel-brostrom/boxmot/releases/download/v13.0.9/MOT17-ablation.zip"

benchmark:
  source: "boxmot/engine/trackeval/data/MOT17-ablation"
  split: "train"
  eval_classes:
    1: pedestrian
  distractor_classes:
    2: person_on_vehicle
    7: static_person
    8: distractor
    12: reflection

